const std = @import("std");
const emptyArgs: []const []const u8 = &.{};

pub const CommandKeywords = struct {
    /// one value keywords
    one: []const []const u8,
    /// multi value keywords
    multi: []const []const u8,
    /// flag
    options: []const []const u8 = &.{},

    pub fn hasArgWithValueKeyword(self: CommandKeywords, word: []const u8) bool {
        for (self.multi) |k| if (std.mem.eql(u8, k, word)) return true;
        for (self.one) |k| if (std.mem.eql(u8, k, word)) return true;
        return false;
    }

    pub fn isOneValueArg(self: CommandKeywords, word: []const u8) bool {
        for (self.one) |k| if (std.mem.eql(u8, k, word)) return true;
        return false;
    }

    pub fn contains(self: CommandKeywords, word: []const u8) bool {
        for (self.multi) |k| if (std.mem.eql(u8, k, word)) return true;
        for (self.options) |k| if (std.mem.eql(u8, k, word)) return true;
        for (self.one) |k| if (std.mem.eql(u8, k, word)) return true;
        return false;
    }
};

pub const gCommandMap = std.StaticStringMapWithEql(CommandKeywords, std.static_string_map.eqlAsciiIgnoreCase).initComptime(.{
    // find_package
    .{ "find_package", .{
        .multi = &.{ "COMPONENTS", "OPTIONAL_COMPONENTS", "NAMES", "CONFIGS", "HINTS", "PATHS", "PATH_SUFFIXES", "REQUIRED" },
        .options = &.{ "EXACT", "QUIET", "MODULE", "CONFIG", "NO_MODULE", "NO_POLICY_SCOPE", "NO_DEFAULT_PATH", "NO_PACKAGE_ROOT_PATH", "NO_CMAKE_PATH", "NO_CMAKE_ENVIRONMENT_PATH", "NO_SYSTEM_ENVIRONMENT_PATH", "NO_CMAKE_PACKAGE_REGISTRY", "NO_CMAKE_BUILDS_PATH", "NO_CMAKE_SYSTEM_PATH", "NO_CMAKE_SYSTEM_PACKAGE_REGISTRY", "CMAKE_FIND_ROOT_PATH_BOTH", "ONLY_CMAKE_FIND_ROOT_PATH", "NO_CMAKE_FIND_ROOT_PATH", "NO_CMAKE_INSTALL_PREFIX", "GLOBAL" },
        .one = emptyArgs,
    } },

    // find_library
    .{ "find_library", .{
        .one = &.{ "DOC", "ENV", "VALIDATOR" },
        .multi = &.{ "NAMES", "HINTS", "PATHS", "PATH_SUFFIXES" },
        .options = &.{ "NAMES_PER_DIR", "NO_DEFAULT_PATH", "NO_PACKAGE_ROOT_PATH", "NO_CMAKE_PATH", "NO_CMAKE_ENVIRONMENT_PATH", "NO_SYSTEM_ENVIRONMENT_PATH", "NO_CMAKE_SYSTEM_PATH", "CMAKE_FIND_ROOT_PATH_BOTH", "ONLY_CMAKE_FIND_ROOT_PATH", "NO_CMAKE_FIND_ROOT_PATH", "REQUIRED", "NO_CMAKE_INSTALL_PREFIX" },
    } },

    // build_command
    .{ "build_command", .{ .one = &.{ "CONFIGURATION", "PARALLEL_LEVEL", "TARGET", "PROJECT_NAME" }, .multi = emptyArgs, .options = emptyArgs } },

    // find_program
    .{ "find_program", .{
        .one = &.{ "DOC", "ENV", "VALIDATOR" },
        .multi = &.{ "NAMES", "NAMES_PER_DIR", "HINTS", "PATHS", "PATH_SUFFIXES", "REGISTRY_VIEW" },
        .options = &.{ "NO_CACHE", "REQUIRED", "NO_DEFAULT_PATH", "NO_PACKAGE_ROOT_PATH", "NO_CMAKE_PATH", "NO_CMAKE_ENVIRONMENT_PATH", "NO_SYSTEM_ENVIRONMENT_PATH", "NO_CMAKE_SYSTEM_PATH", "NO_CMAKE_INSTALL_PREFIX", "CMAKE_FIND_ROOT_PATH_BOTH", "ONLY_CMAKE_FIND_ROOT_PATH", "NO_CMAKE_FIND_ROOT_PATH" },
    } },

    // target_link_libraries
    .{ "target_link_libraries", .{ .multi = &.{ "PRIVATE", "PUBLIC", "INTERFACE", "LINK_PUBLIC", "LINK_PRIVATE", "LINK_INTERFACE_LIBRARIES" }, .options = emptyArgs, .one = emptyArgs } },
    // target_compile_definitions
    .{ "target_compile_definitions", .{ .multi = &.{ "PRIVATE", "PUBLIC", "INTERFACE" }, .options = emptyArgs, .one = emptyArgs } },
    // target_precompile_headers
    .{ "target_precompile_headers", .{ .multi = &.{ "PRIVATE", "PUBLIC", "INTERFACE" }, .options = emptyArgs, .one = &.{"REUSE_FROM"} } },
    // target_include_directories
    .{ "target_include_directories", .{ .multi = &.{ "PRIVATE", "PUBLIC", "INTERFACE" }, .options = &.{ "BEFORE", "SYSTEM", "AFTER" }, .one = emptyArgs } },
    // target_include_options
    .{ "target_include_options", .{ .multi = &.{ "PRIVATE", "PUBLIC", "INTERFACE" }, .options = emptyArgs, .one = emptyArgs } },
    // target_compile_features
    .{ "target_compile_features", .{ .multi = &.{ "PRIVATE", "PUBLIC", "INTERFACE" }, .options = emptyArgs, .one = emptyArgs } },
    // target_compile_options
    .{ "target_compile_options", .{ .multi = &.{ "PRIVATE", "PUBLIC", "INTERFACE" }, .options = &.{"BEFORE"}, .one = emptyArgs } },
    // set_target_properties
    .{ "set_target_properties", .{ .multi = &.{"PROPERTIES"}, .options = emptyArgs, .one = emptyArgs } },
    // set_directory_properties
    .{ "set_directory_properties", .{ .multi = &.{"PROPERTIES"}, .options = emptyArgs, .one = emptyArgs } },
    // set_tests_properties
    .{ "set_tests_properties", .{ .multi = &.{"PROPERTIES"}, .one = &.{"DIRECTORY"}, .options = emptyArgs } },
    // set_source_files_properties
    .{ "set_source_files_properties", .{ .multi = &.{ "PROPERTIES", "DIRECTORY", "TARGET_DIRECTORY" }, .options = emptyArgs, .one = emptyArgs } },
    // add_custom_target
    .{ "add_custom_target", .{
        .multi = &.{ "COMMAND", "DEPENDS", "BYPRODUCTS", "SOURCES" },
        .options = &.{ "ALL", "COMMAND_EXPAND_LISTS", "VERBATIM", "USES_TERMINAL" },
        .one = &.{ "WORKING_DIRECTORY", "COMMENT", "JOB_POOL", "JOB_SERVER_AWARE" },
    } },
    // add_custom_command
    .{ "add_custom_command", .{
        .multi = &.{ "TARGET", "OUTPUT", "COMMAND", "ARGS", "DEPENDS", "BYPRODUCTS", "IMPLICIT_DEPENDS" },
        .options = &.{ "VERBATIM", "APPEND", "USES_TERMINAL", "COMMAND_EXPAND_LISTS", "DEPENDS_EXPLICIT_ONLY", "CODEGEN", "PRE_BUILD", "PRE_LINK", "POST_BUILD" },
        .one = &.{ "MAIN_DEPENDENCY", "WORKING_DIRECTORY", "COMMENT", "DEPFILE", "JOB_POOL", "JOB_SERVER_AWARE" },
    } },
    // add_test
    .{ "add_test", .{ .multi = &.{ "COMMAND", "CONFIGURATIONS" }, .options = &.{"COMMAND_EXPAND_LISTS"}, .one = &.{ "NAME", "WORKING_DIRECTORY" } } },
    // target_sources
    .{ "target_sources", .{ .multi = &.{ "INTERFACE", "PUBLIC", "PRIVATE" }, .options = emptyArgs, .one = emptyArgs } },

    // BEGIN builtin Modules
    .{ "find_package_check_version", .{ .options = &.{ "HANDLE_VERSION_RANGE", "NO_AUTHOR_WARNING_VERSION_RANGE" }, .one = &.{"RESULT_MESSAGE_VARIABLE"}, .multi = emptyArgs } },
    .{ "find_package_handle_standard_args", .{ .options = &.{ "CONFIG_MODE", "HANDLE_COMPONENTS", "NAME_MISMATCHED", "HANDLE_VERSION_RANGE" }, .one = &.{ "FAIL_MESSAGE", "REASON_FAILURE_MESSAGE", "VERSION_VAR", "FOUND_VAR" }, .multi = &.{"REQUIRED_VARS"} } },
    .{ "protobuf_generate", .{ .options = &.{ "APPEND_PATH", "DESCRIPTORS" }, .one = &.{ "LANGUAGE", "OUT_VAR", "EXPORT_MACRO", "PROTOC_OUT_DIR", "PLUGIN", "PLUGIN_OPTIONS", "DEPENDENCIES" }, .multi = &.{ "PROTOS", "IMPORT_DIRS", "GENERATE_EXTENSIONS", "PROTOC_OPTIONS" } } },
    .{ "protobuf_generate_cpp", .{ .options = emptyArgs, .one = &.{ "EXPORT_MACRO", "DESCRIPTORS" }, .multi = emptyArgs } },
    .{ "cmake_add_fortran_subdirectory", .{ .options = &.{"NO_EXTERNAL_INSTALL"}, .one = &.{ "PROJECT", "ARCHIVE_DIR", "RUNTIME_DIR" }, .multi = &.{ "LIBRARIES", "LINK_LIBRARIES", "CMAKE_COMMAND_LINE" } } },
    .{ "cmake_check_linker_flag", .{ .options = emptyArgs, .one = &.{"OUTPUT_VARIABLE"}, .multi = emptyArgs } },
    .{ "cmake_check_compiler_flag", .{ .options = emptyArgs, .one = &.{"OUTPUT_VARIABLE"}, .multi = emptyArgs } },
    .{ "cmake_try_compiler_or_linker_flag", .{ .options = emptyArgs, .one = &.{ "SRC_EXT", "COMMAND_PATTERN", "OUTPUT_VARIABLE" }, .multi = &.{"FAIL_REGEX"} } },
    .{ "cmake_expand_imported_targets", .{ .options = emptyArgs, .one = &.{"CONFIGURATION"}, .multi = &.{"LIBRARIES"} } },
    .{ "cmake_parse_implicit_link_info2", .{ .options = emptyArgs, .one = &.{ "LANGUAGE", "COMPUTE_IMPLICIT_LIBS", "COMPUTE_IMPLICIT_DIRS", "COMPUTE_IMPLICIT_FWKS", "COMPUTE_IMPLICIT_OBJECTS", "COMPUTE_LINKER" }, .multi = emptyArgs } },
    .{ "cmake_parse_implicit_link_info", .{ .options = emptyArgs, .one = &.{ "LANGUAGE", "COMPUTE_IMPLICIT_OBJECTS" }, .multi = emptyArgs } },
    .{ "perl_get_info", .{ .options = &.{"IS_PATH"}, .one = emptyArgs, .multi = emptyArgs } },
    .{ "externaldata_add_test", .{ .options = emptyArgs, .one = &.{"SHOW_PROGRESS"}, .multi = emptyArgs } },
    .{ "externaldata_add_target", .{ .options = emptyArgs, .one = &.{"SHOW_PROGRESS"}, .multi = emptyArgs } },
    .{ "export_jars", .{ .options = emptyArgs, .one = &.{ "FILE", "NAMESPACE" }, .multi = &.{"TARGETS"} } },
    .{ "install_jar_exports", .{ .options = emptyArgs, .one = &.{ "FILE", "DESTINATION", "COMPONENT", "NAMESPACE" }, .multi = &.{"TARGETS"} } },
    .{ "create_javadoc", .{ .options = emptyArgs, .one = &.{ "TARGET", "GENERATED_FILES", "OUTPUT_NAME", "OUTPUT_DIR" }, .multi = &.{ "CLASSES", "CLASSPATH", "DEPENDS" } } },
    .{ "add_jar", .{ .options = emptyArgs, .one = &.{ "ENTRY_POINT", "MANIFEST", "OUTPUT_DIR", "", "OUTPUT_NAME", "VERSION" }, .multi = &.{ "GENERATE_NATIVE_HEADERS", "INCLUDE_JARS", "RESOURCES", "SOURCES" } } },
    .{ "install_jar", .{ .options = emptyArgs, .one = &.{ "DESTINATION", "COMPONENT" }, .multi = emptyArgs } },
    .{ "find_jar", .{ .options = emptyArgs, .one = &.{ "TARGET", "GENERATED_FILES", "OUTPUT_NAME", "OUTPUT_DIR" }, .multi = &.{ "CLASSES", "CLASSPATH", "DEPENDS" } } },
    .{ "install_jni_symlink", .{ .options = emptyArgs, .one = &.{ "DESTINATION", "COMPONENT" }, .multi = emptyArgs } },
    .{ "create_javah", .{ .options = emptyArgs, .one = &.{ "TARGET", "GENERATED_FILES", "OUTPUT_NAME", "OUTPUT_DIR" }, .multi = &.{ "CLASSES", "CLASSPATH", "DEPENDS" } } },
    .{ "check_ipo_supported", .{ .options = emptyArgs, .one = &.{ "RESULT", "OUTPUT" }, .multi = &.{"LANGUAGES"} } },
    .{ "matlab_get_release_name_from_version", .{ .options = emptyArgs, .one = &.{"REGISTRY_VIEW"}, .multi = emptyArgs } },
    .{ "matlab_add_mex", .{ .options = &.{ "EXECUTABLE", "MODULE", "SHARED", "R2017b", "R2018a", "EXCLUDE_FROM_ALL", "NO_IMPLICIT_LINK_TO_MATLAB_LIBRARIES" }, .one = &.{ "NAME", "DOCUMENTATION", "OUTPUT_NAME" }, .multi = &.{ "LINK_TO", "SRC" } } },
    .{ "matlab_get_all_valid_matlab_roots_from_registry", .{ .options = emptyArgs, .one = &.{"REGISTRY_VIEW"}, .multi = emptyArgs } },
    .{ "matlab_get_mex_suffix", .{ .options = &.{"NO_UNITTEST_FRAMEWORK"}, .one = &.{ "NAME", "UNITTEST_FILE", "TIMEOUT", "WORKING_DIRECTORY", "UNITTEST_PRECOMMAND", "CUSTOM_TEST_COMMAND" }, .multi = &.{ "ADDITIONAL_PATH", "MATLAB_ADDITIONAL_STARTUP_OPTIONS", "TEST_ARGS" } } },
    .{ "matlab_get_version_from_matlab_run", .{ .options = &.{"NO_UNITTEST_FRAMEWORK"}, .one = &.{ "NAME", "UNITTEST_FILE", "TIMEOUT", "WORKING_DIRECTORY", "UNITTEST_PRECOMMAND", "CUSTOM_TEST_COMMAND" }, .multi = &.{ "ADDITIONAL_PATH", "MATLAB_ADDITIONAL_STARTUP_OPTIONS", "TEST_ARGS" } } },
    .{ "matlab_add_unit_test", .{ .options = &.{"NO_UNITTEST_FRAMEWORK"}, .one = &.{ "NAME", "UNITTEST_FILE", "TIMEOUT", "WORKING_DIRECTORY", "UNITTEST_PRECOMMAND", "CUSTOM_TEST_COMMAND" }, .multi = &.{ "ADDITIONAL_PATH", "MATLAB_ADDITIONAL_STARTUP_OPTIONS", "TEST_ARGS" } } },
    .{ "matlab_extract_all_installed_versions_from_registry", .{ .options = emptyArgs, .one = &.{"REGISTRY_VIEW"}, .multi = emptyArgs } },
    .{ "write_basic_config_version_file", .{ .options = &.{"ARCH_INDEPENDENT"}, .one = &.{ "VERSION", "COMPATIBILITY" }, .multi = emptyArgs } },
    .{ "doxygen_quote_value", .{ .options = &.{ "ALL", "USE_STAMP_FILE" }, .one = &.{ "WORKING_DIRECTORY", "COMMENT", "CONFIG_FILE" }, .multi = emptyArgs } },
    .{ "doxygen_add_docs", .{ .options = &.{ "ALL", "USE_STAMP_FILE" }, .one = &.{ "WORKING_DIRECTORY", "COMMENT", "CONFIG_FILE" }, .multi = emptyArgs } },
    .{ "doxygen_list_to_quoted_strings", .{ .options = &.{ "ALL", "USE_STAMP_FILE" }, .one = &.{ "WORKING_DIRECTORY", "COMMENT", "CONFIG_FILE" }, .multi = emptyArgs } },
    .{ "write_compiler_detection_header", .{ .options = &.{ "ALLOW_UNKNOWN_COMPILERS", "ALLOW_UNKNOWN_COMPILER_VERSIONS" }, .one = &.{ "VERSION", "EPILOG", "PROLOG", "OUTPUT_FILES_VAR", "OUTPUT_DIR" }, .multi = &.{ "COMPILERS", "FEATURES", "BARE_FEATURES" } } },
    .{ "env_module", .{ .options = emptyArgs, .one = &.{ "OUTPUT_VARIABLE", "RESULT_VARIABLE" }, .multi = &.{"COMMAND"} } },
    .{ "env_module_swap", .{ .options = emptyArgs, .one = &.{ "OUTPUT_VARIABLE", "RESULT_VARIABLE" }, .multi = emptyArgs } },
    .{ "compiler_id_detection", .{ .options = &.{ "ID_STRING", "VERSION_STRINGS", "ID_DEFINE", "PLATFORM_DEFAULT_COMPILER" }, .one = &.{"PREFIX"}, .multi = emptyArgs } },
    .{ "generate_apple_architecture_selection_file", .{ .options = emptyArgs, .one = &.{ "INSTALL_DESTINATION", "INSTALL_PREFIX", "UNIVERSAL_INCLUDE_FILE", "ERROR_VARIABLE" }, .multi = &.{ "SINGLE_ARCHITECTURES", "SINGLE_ARCHITECTURE_INCLUDE_FILES", "UNIVERSAL_ARCHITECTURES" } } },
    .{ "generate_apple_platform_selection_file", .{ .options = emptyArgs, .multi = emptyArgs, .one = &.{ "INSTALL_DESTINATION", "INSTALL_PREFIX", "INSTALL_PREFIX", "MACOS_INCLUDE_FILE", "IOS_INCLUDE_FILE", "IOS_SIMULATOR_INCLUDE_FILE", "IOS_CATALYST_INCLUDE_FILE", "TVOS_INCLUDE_FILE", "TVOS_SIMULATOR_INCLUDE_FILE", "WATCHOS_INCLUDE_FILE", "WATCHOS_SIMULATOR_INCLUDE_FILE", "VISIONOS_INCLUDE_FILE", "VISIONOS_SIMULATOR_INCLUDE_FILE", "ERROR_VARIABLE" } } },
    .{ "configure_package_config_file", .{ .options = &.{ "NO_SET_AND_CHECK_MACRO", "NO_CHECK_REQUIRED_COMPONENTS_MACRO" }, .one = &.{ "INSTALL_DESTINATION", "INSTALL_PREFIX" }, .multi = &.{"PATH_VARS"} } },
    .{ "swig_add_source_to_module", .{ .options = &.{"NO_PROXY"}, .one = &.{ "LANGUAGE", "TYPE", "OUTPUT_DIR", "OUTFILE_DIR" }, .multi = &.{"SOURCES"} } },
    .{ "swig_get_extra_output_files", .{ .options = &.{"NO_PROXY"}, .one = &.{ "LANGUAGE", "TYPE", "OUTPUT_DIR", "OUTFILE_DIR" }, .multi = &.{"SOURCES"} } },
    .{ "swig_add_library", .{ .options = &.{"NO_PROXY"}, .one = &.{ "LANGUAGE", "TYPE", "OUTPUT_DIR", "OUTFILE_DIR" }, .multi = &.{"SOURCES"} } },
    .{ "ctest_coverage_collect_gcov", .{ .options = &.{ "QUIET", "GLOB", "DELETE" }, .one = &.{ "TARBALL", "SOURCE", "BUILD", "GCOV_COMMAND", "TARBALL_COMPRESSION" }, .multi = &.{"GCOV_OPTIONS"} } },
    .{ "check_pie_supported", .{ .options = emptyArgs, .one = &.{"OUTPUT_VARIABLE"}, .multi = &.{"LANGUAGES"} } },
    .{ "execute_adb_command", .{ .options = emptyArgs, .one = &.{ "FILES_DEST", "LIBS_DEST", "DEV_TEST_DIR", "DEV_OBJ_STORE" }, .multi = &.{ "FILES", "LIBS" } } },
    .{ "push_and_link", .{ .options = emptyArgs, .one = &.{ "FILES_DEST", "LIBS_DEST", "DEV_TEST_DIR", "DEV_OBJ_STORE" }, .multi = &.{ "FILES", "LIBS" } } },
    .{ "android_push_test_files_to_device", .{ .options = emptyArgs, .one = &.{ "FILES_DEST", "LIBS_DEST", "DEV_TEST_DIR", "DEV_OBJ_STORE" }, .multi = &.{ "FILES", "LIBS" } } },
    .{ "filename_regex", .{ .options = emptyArgs, .one = &.{ "FILES_DEST", "LIBS_DEST", "DEV_TEST_DIR", "DEV_OBJ_STORE" }, .multi = &.{ "FILES", "LIBS" } } },
    .{ "cmake_print_properties", .{ .options = emptyArgs, .one = emptyArgs, .multi = &.{"PROPERTIES"} } },
    .{ "cmake_print_variables", .{ .options = emptyArgs, .one = emptyArgs, .multi = &.{"PROPERTIES"} } },
    .{ "fetchcontent_declare", .{ .options = emptyArgs, .one = &.{ "GIT_REPOSITORY", "SVN_REPOSITORY", "DOWNLOAD_NO_EXTRACT", "DOWNLOAD_EXTRACT_TIMESTAMP", "BINARY_DIR", "SOURCE_DIR" }, .multi = emptyArgs } },
    .{ "fetchcontent_getproperties", .{ .options = &.{""}, .one = &.{ "SOURCE_DIR", "BINARY_DIR", "POPULATED" }, .multi = &.{""} } },
    .{ "fetchcontent_setpopulated", .{ .options = emptyArgs, .one = &.{ "SOURCE_DIR", "BINARY_DIR" }, .multi = emptyArgs } },
    .{ "verify_bundle_prerequisites", .{ .options = emptyArgs, .one = emptyArgs, .multi = &.{"IGNORE_ITEM"} } },
    .{ "get_bundle_keys", .{ .options = emptyArgs, .one = emptyArgs, .multi = &.{"IGNORE_ITEM"} } },
    .{ "get_bundle_main_executable", .{ .options = emptyArgs, .one = emptyArgs, .multi = &.{"IGNORE_ITEM"} } },
    .{ "get_bundle_and_executable", .{ .options = emptyArgs, .one = emptyArgs, .multi = &.{"IGNORE_ITEM"} } },
    .{ "link_resolved_item_into_bundle", .{ .options = emptyArgs, .one = emptyArgs, .multi = &.{"IGNORE_ITEM"} } },
    .{ "get_dotapp_dir", .{ .options = emptyArgs, .one = emptyArgs, .multi = &.{"IGNORE_ITEM"} } },
    .{ "fixup_bundle", .{ .options = emptyArgs, .one = emptyArgs, .multi = &.{"IGNORE_ITEM"} } },
    .{ "copy_resolved_framework_into_bundle", .{ .options = emptyArgs, .one = emptyArgs, .multi = &.{"IGNORE_ITEM"} } },
    .{ "clear_bundle_keys", .{ .options = emptyArgs, .one = emptyArgs, .multi = &.{"IGNORE_ITEM"} } },
    .{ "verify_bundle_symlinks", .{ .options = emptyArgs, .one = emptyArgs, .multi = &.{"IGNORE_ITEM"} } },
    .{ "verify_app", .{ .options = emptyArgs, .one = emptyArgs, .multi = &.{"IGNORE_ITEM"} } },
    .{ "get_item_key", .{ .options = emptyArgs, .one = emptyArgs, .multi = &.{"IGNORE_ITEM"} } },
    .{ "copy_resolved_item_into_bundle", .{ .options = emptyArgs, .one = emptyArgs, .multi = &.{"IGNORE_ITEM"} } },
    .{ "get_item_rpaths", .{ .options = emptyArgs, .one = emptyArgs, .multi = &.{"IGNORE_ITEM"} } },
    .{ "set_bundle_key_values", .{ .options = emptyArgs, .one = emptyArgs, .multi = &.{"IGNORE_ITEM"} } },
    .{ "get_bundle_all_executables", .{ .options = emptyArgs, .one = emptyArgs, .multi = &.{"IGNORE_ITEM"} } },
    .{ "copy_and_fixup_bundle", .{ .options = emptyArgs, .one = emptyArgs, .multi = &.{"IGNORE_ITEM"} } },
    .{ "fixup_bundle_item", .{ .options = emptyArgs, .one = emptyArgs, .multi = &.{"IGNORE_ITEM"} } },
    .{ "gtest_discover_tests_impl", .{ .options = &.{""}, .one = &.{ "NO_PRETTY_TYPES", "NO_PRETTY_VALUES", "TEST_EXECUTABLE", "TEST_WORKING_DIR", "TEST_PREFIX", "TEST_SUFFIX", "TEST_LIST", "CTEST_FILE", "TEST_DISCOVERY_TIMEOUT", "TEST_XML_OUTPUT_DIR", "TEST_FILTER", "TEST_EXTRA_ARGS", "TEST_DISCOVERY_EXTRA_ARGS", "TEST_PROPERTIES", "TEST_EXECUTOR" }, .multi = &.{""} } },
    .{ "generate_testname_guards", .{ .options = &.{""}, .one = &.{ "NO_PRETTY_TYPES", "NO_PRETTY_VALUES", "TEST_EXECUTABLE", "TEST_WORKING_DIR", "TEST_PREFIX", "TEST_SUFFIX", "TEST_LIST", "CTEST_FILE", "TEST_DISCOVERY_TIMEOUT", "TEST_XML_OUTPUT_DIR", "TEST_FILTER", "TEST_EXTRA_ARGS", "TEST_DISCOVERY_EXTRA_ARGS", "TEST_PROPERTIES", "TEST_EXECUTOR" }, .multi = &.{""} } },
    .{ "add_command", .{ .options = &.{""}, .one = &.{ "NO_PRETTY_TYPES", "NO_PRETTY_VALUES", "TEST_EXECUTABLE", "TEST_WORKING_DIR", "TEST_PREFIX", "TEST_SUFFIX", "TEST_LIST", "CTEST_FILE", "TEST_DISCOVERY_TIMEOUT", "TEST_XML_OUTPUT_DIR", "TEST_FILTER", "TEST_EXTRA_ARGS", "TEST_DISCOVERY_EXTRA_ARGS", "TEST_PROPERTIES", "TEST_EXECUTOR" }, .multi = &.{""} } },
    .{ "escape_square_brackets", .{ .options = &.{""}, .one = &.{ "NO_PRETTY_TYPES", "NO_PRETTY_VALUES", "TEST_EXECUTABLE", "TEST_WORKING_DIR", "TEST_PREFIX", "TEST_SUFFIX", "TEST_LIST", "CTEST_FILE", "TEST_DISCOVERY_TIMEOUT", "TEST_XML_OUTPUT_DIR", "TEST_FILTER", "TEST_EXTRA_ARGS", "TEST_DISCOVERY_EXTRA_ARGS", "TEST_PROPERTIES", "TEST_EXECUTOR" }, .multi = &.{""} } },
    .{ "cpack_append_string_variable_set_command", .{ .options = &.{ "HIDDEN", "REQUIRED", "DISABLED", "DOWNLOADED" }, .one = &.{ "DISPLAY_NAME", "DESCRIPTION", "GROUP", "ARCHIVE_FILE", "PLIST" }, .multi = &.{ "DEPENDS", "INSTALL_TYPES" } } },
    .{ "cpack_append_variable_set_command", .{ .options = &.{ "HIDDEN", "REQUIRED", "DISABLED", "DOWNLOADED" }, .one = &.{ "DISPLAY_NAME", "DESCRIPTION", "GROUP", "ARCHIVE_FILE", "PLIST" }, .multi = &.{ "DEPENDS", "INSTALL_TYPES" } } },
    .{ "android_add_test_data", .{ .options = emptyArgs, .one = &.{ "FILES_DEST", "LIBS_DEST", "DEVICE_OBJECT_STORE", "DEVICE_TEST_DIR" }, .multi = &.{ "FILES", "LIBS", "NO_LINK_REGEX" } } },
    .{ "gtest_add_tests", .{ .options = &.{"SKIP_DEPENDENCY"}, .one = &.{ "TARGET", "WORKING_DIRECTORY", "TEST_PREFIX", "TEST_SUFFIX", "TEST_LIST" }, .multi = &.{ "SOURCES", "EXTRA_ARGS" } } },
    .{ "gtest_discover_tests", .{ .options = &.{ "NO_PRETTY_TYPES", "NO_PRETTY_VALUES" }, .one = &.{ "TEST_PREFIX", "TEST_SUFFIX", "WORKING_DIRECTORY", "TEST_LIST", "DISCOVERY_TIMEOUT", "XML_OUTPUT_DIR", "DISCOVERY_MODE" }, .multi = &.{ "EXTRA_ARGS", "DISCOVERY_EXTRA_ARGS", "PROPERTIES", "TEST_FILTER" } } },
    .{ "squish_v4_add_test", .{ .options = emptyArgs, .one = &.{ "AUT", "SUITE", "TEST", "SETTINGSGROUP", "PRE_COMMAND", "POST_COMMAND" }, .multi = emptyArgs } },
    .{ "Python_add_library", .{ .options = &.{ "STATIC", "SHARED", "MODULE", "WITH_SOABI" }, .one = &.{"USE_SABI"}, .multi = emptyArgs } },
    // END

    // 3rdparty stuff
    .{ "kdoctools_create_handbook", .{ .options = emptyArgs, .one = &.{ "INSTALL_DESTINATION", "SUBDIR" }, .multi = emptyArgs } },
    .{ "kdoctools_create_manpage", .{ .options = emptyArgs, .one = &.{"INSTALL_DESTINATION"}, .multi = emptyArgs } },
    .{ "qt6_generate_wayland_protocol_client_sources", .{ .options = &.{ "NO_INCLUDE_CORE_ONLY", "PRIVATE_CODE", "PUBLIC_CODE" }, .one = &.{"__QT_INTERNAL_WAYLAND_INCLUDE_DIR"}, .multi = &.{"FILES"} } },
    .{ "qt_add_shaders", .{ .options = emptyArgs, .one = &.{"OUTPUT_TARGETS"}, .multi = emptyArgs } },
    .{ "qt6_add_shaders", .{ .options = emptyArgs, .one = &.{"OUTPUT_TARGETS"}, .multi = emptyArgs } },
    .{ "qt_create_translation", .{ .options = emptyArgs, .one = &.{"QM_FILES_OUTPUT_VARIABLE"}, .multi = &.{"OPTIONS"} } },
    .{ "qt_add_translations", .{ .options = &.{ "", "IMMEDIATE_CALL", "NO_GENERATE_PLURALS_TS_FILE" }, .one = &.{ "TS_FILES_OUTPUT_VARIABLE", "QM_FILES_OUTPUT_VARIABLE", "__QT_INTERNAL_DEFAULT_QM_OUT_DIR", "LUPDATE_TARGET", "LRELEASE_TARGET", "RESOURCE_PREFIX", "OUTPUT_TARGETS" }, .multi = &.{ "OUTPUT_TARGETS", "TARGETS", "SOURCE_TARGETS", "TS_FILES", "TS_FILE_BASE", "TS_FILE_DIR", "PLURALS_TS_FILE", "SOURCES", "INCLUDE_DIRECTORIES", "LUPDATE_OPTIONS", "LRELEASE_OPTIONS" } } },
    .{ "qt6_create_translation", .{ .options = emptyArgs, .one = emptyArgs, .multi = &.{"OPTIONS"} } },
    .{ "qt_add_translation", .{ .options = emptyArgs, .one = &.{"QM_FILES_OUTPUT_VARIABLE"}, .multi = &.{ "OPTIONS", "__QT_INTERNAL_TIMESTAMP_FILES" } } },
    .{ "qt_collect_translation_source_targets", .{ .options = &.{""}, .one = &.{ "QM_FILES_OUTPUT_VARIABLE", "DIRECTORY" }, .multi = &.{""} } },
    .{ "qt6_collect_translation_source_targets", .{ .options = &.{""}, .one = &.{"DIRECTORY"}, .multi = &.{""} } },
    .{ "qt6_add_lupdate", .{ .options = &.{"NO_GLOBAL_TARGET"}, .one = &.{ "PLURALS_TS_FILE", "LUPDATE_TARGET" }, .multi = &.{ "SOURCE_TARGETS", "TS_FILES", "SOURCES", "INCLUDE_DIRECTORIES", "OPTIONS" } } },
    .{ "qt6_add_translations", .{ .options = &.{ "IMMEDIATE_CALL", "NO_GENERATE_PLURALS_TS_FILE" }, .one = &.{ "__QT_INTERNAL_DEFAULT_QM_OUT_DIR", "LUPDATE_TARGET", "LRELEASE_TARGET", "TS_FILES_OUTPUT_VARIABLE", "QM_FILES_OUTPUT_VARIABLE", "RESOURCE_PREFIX", "OUTPUT_TARGETS" }, .multi = &.{ "TARGETS", "SOURCE_TARGETS", "TS_FILES", "TS_FILE_BASE", "TS_FILE_DIR", "PLURALS_TS_FILE", "SOURCES", "INCLUDE_DIRECTORIES", "LUPDATE_OPTIONS", "LRELEASE_OPTIONS" } } },
    .{ "qt_add_lrelease", .{ .options = &.{ "NO_TARGET_DEPENDENCY", "EXCLUDE_FROM_ALL", "NO_GLOBAL_TARGET" }, .one = &.{ "QM_FILES_OUTPUT_VARIABLE", "__QT_INTERNAL_DEFAULT_QM_OUT_DIR", "LRELEASE_TARGET" }, .multi = &.{ "TS_FILES", "OPTIONS" } } },
    .{ "qt6_add_lrelease", .{ .options = &.{ "NO_TARGET_DEPENDENCY", "EXCLUDE_FROM_ALL", "NO_GLOBAL_TARGET" }, .one = &.{ "__QT_INTERNAL_DEFAULT_QM_OUT_DIR", "LRELEASE_TARGET", "QM_FILES_OUTPUT_VARIABLE" }, .multi = &.{ "TS_FILES", "OPTIONS" } } },
    .{ "qt_add_lupdate", .{ .options = &.{"NO_GLOBAL_TARGET"}, .one = &.{ "QM_FILES_OUTPUT_VARIABLE", "PLURALS_TS_FILE", "LUPDATE_TARGET" }, .multi = &.{ "SOURCE_TARGETS", "TS_FILES", "SOURCES", "INCLUDE_DIRECTORIES", "OPTIONS" } } },
    .{ "qt6_add_translation", .{ .options = emptyArgs, .one = emptyArgs, .multi = &.{ "OPTIONS", "__QT_INTERNAL_TIMESTAMP_FILES" } } },
    .{ "qt6_add_materials", .{ .options = emptyArgs, .one = &.{"PREFIX"}, .multi = &.{"FILES"} } },
    .{ "qt6_add_lightprobe_images", .{ .options = emptyArgs, .one = &.{ "PREFIX", "BASE", "_QT_INTERNAL" }, .multi = &.{ "FILES", "OUTPUTS" } } },
    .{ "qt5_wrap_ui", .{ .options = emptyArgs, .one = emptyArgs, .multi = &.{"OPTIONS"} } },
    .{ "kcoreaddons_add_plugin", .{ .options = &.{"STATIC"}, .one = &.{ "JSON", "INSTALL_NAMESPACE" }, .multi = &.{"SOURCES"} } },
    .{ "kcoreaddons_desktop_to_json", .{ .options = &.{ "COMPAT_MODE", "DEFAULT_SERVICE_TYPE" }, .one = &.{ "OUTPUT_DIR", "OUTPUT_FILE" }, .multi = &.{"SERVICE_TYPES"} } },
    .{ "kcoreaddons_target_static_plugins", .{ .options = emptyArgs, .one = &.{ "LINK_OPTION", "NAMESPACE", "TARGETS" }, .multi = emptyArgs } },
    .{ "kcoreaddons_desktop_to_json_crosscompilation_args", .{ .options = &.{"STATIC"}, .one = &.{ "JSON", "INSTALL_NAMESPACE" }, .multi = &.{"SOURCES"} } },
    .{ "qt6_generate_wayland_protocol_server_sources", .{ .options = &.{ "PUBLIC_CODE", "PRIVATE_CODE" }, .one = &.{"__QT_INTERNAL_WAYLAND_INCLUDE_DIR"}, .multi = &.{"FILES"} } },
    .{ "qt6_wrap_cpp", .{ .options = &.{""}, .one = &.{"__QT_INTERNAL_OUTPUT_MOC_JSON_FILES"}, .multi = &.{""} } },
    .{ "qt6_generate_moc", .{ .options = &.{""}, .one = &.{"__QT_INTERNAL_OUTPUT_MOC_JSON_FILES"}, .multi = &.{""} } },
    .{ "qt6_add_library", .{ .options = &.{"MANUAL_FINALIZATION"}, .one = emptyArgs, .multi = emptyArgs } },
    .{ "qt_extract_metatypes", .{ .options = &.{"__QT_INTERNAL_INSTALL"}, .one = &.{ "OUTPUT_FILES", "__QT_INTERNAL_INSTALL_DIR" }, .multi = &.{"MANUAL_MOC_JSON_FILES"} } },
    .{ "qt6_policy", .{ .options = emptyArgs, .one = &.{ "REQUIRES", "SUPPORTS_UP_TO", "I18N_SOURCE_LANGUAGE" }, .multi = &.{"I18N_TRANSLATED_LANGUAGES"} } },
    .{ "qt_add_big_resources", .{ .options = &.{"MANUAL_FINALIZATION"}, .one = emptyArgs, .multi = &.{"OPTIONS"} } },
    .{ "qt_import_plugins", .{ .options = &.{ "ENABLE", "DISABLE", "NO_DEFAULT" }, .one = emptyArgs, .multi = &.{ "MODES", "INCLUDE", "EXCLUDE", "INCLUDE_BY_TYPE", "EXCLUDE_BY_TYPE" } } },
    .{ "qt6_add_resources", .{ .options = emptyArgs, .one = &.{"OUTPUT_TARGETS"}, .multi = emptyArgs } },
    .{ "qt_add_binary_resources", .{ .options = emptyArgs, .one = &.{ "OUTPUT_TARGETS", "DESTINATION" }, .multi = &.{"OPTIONS"} } },
    .{ "qt_add_plugin", .{ .options = emptyArgs, .one = &.{"OUTPUT_TARGETS"}, .multi = emptyArgs } },
    .{ "qt_finalize_target", .{ .options = &.{"NO_DEFAULT"}, .one = emptyArgs, .multi = &.{ "INCLUDE", "EXCLUDE", "INCLUDE_BY_TYPE", "EXCLUDE_BY_TYPE" } } },
    .{ "qt6_set_finalizer_mode", .{ .options = &.{ "ENABLE", "DISABLE" }, .one = emptyArgs, .multi = &.{"MODES"} } },
    .{ "qt_wrap_cpp", .{ .options = &.{""}, .one = &.{ "DESTINATION", "__QT_INTERNAL_OUTPUT_MOC_JSON_FILES" }, .multi = &.{ "OPTIONS", "" } } },
    .{ "qt6_disable_unicode_defines", .{ .options = emptyArgs, .one = &.{ "FUNCTION_NAME", "NAME", "OUTPUT_SCRIPT", "SKIP_REASON", "TARGET" }, .multi = emptyArgs } },
    .{ "qt6_add_binary_resources", .{ .options = emptyArgs, .one = &.{"DESTINATION"}, .multi = &.{"OPTIONS"} } },
    .{ "qt_finalize_executable", .{ .options = &.{"NO_DEFAULT"}, .one = emptyArgs, .multi = &.{ "INCLUDE", "EXCLUDE", "INCLUDE_BY_TYPE", "EXCLUDE_BY_TYPE" } } },
    .{ "qt6_generate_deploy_script", .{ .options = &.{""}, .one = &.{ "CONTENT", "OUTPUT_SCRIPT", "NAME", "TARGET", "FILENAME_VARIABLE" }, .multi = &.{""} } },
    .{ "qt6_generate_deploy_app_script", .{ .options = &.{ "NO_TRANSLATIONS", "NO_COMPILER_RUNTIME", "NO_UNSUPPORTED_PLATFORM_ERROR" }, .one = &.{ "TARGET", "OUTPUT_SCRIPT", "FILENAME_VARIABLE" }, .multi = emptyArgs } },
    .{ "qt6_import_plugins", .{ .options = &.{"NO_DEFAULT"}, .one = emptyArgs, .multi = &.{ "INCLUDE", "EXCLUDE", "INCLUDE_BY_TYPE", "EXCLUDE_BY_TYPE" } } },
    .{ "qt_add_library", .{ .options = &.{ "INTERFACE_ONLY", "PRIVATE_ONLY", "MANUAL_FINALIZATION" }, .one = emptyArgs, .multi = &.{"PROPERTIES"} } },
    .{ "qt_allow_non_utf8_sources", .{ .options = &.{ "INTERFACE_ONLY", "PRIVATE_ONLY" }, .one = emptyArgs, .multi = &.{"PROPERTIES"} } },
    .{ "qt6_extract_metatypes", .{ .options = &.{"__QT_INTERNAL_INSTALL"}, .one = &.{ "__QT_INTERNAL_INSTALL_DIR", "OUTPUT_FILES" }, .multi = &.{"MANUAL_MOC_JSON_FILES"} } },
    .{ "qt_generate_moc", .{ .options = &.{""}, .one = &.{"__QT_INTERNAL_OUTPUT_MOC_JSON_FILES"}, .multi = &.{""} } },
    .{ "qt6_add_big_resources", .{ .options = emptyArgs, .one = emptyArgs, .multi = &.{"OPTIONS"} } },
    .{ "qt6_finalize_target", .{ .options = &.{"NO_DEFAULT"}, .one = emptyArgs, .multi = &.{ "INCLUDE", "EXCLUDE", "INCLUDE_BY_TYPE", "EXCLUDE_BY_TYPE" } } },
    .{ "qt_add_resources", .{ .options = emptyArgs, .one = &.{"OUTPUT_TARGETS"}, .multi = emptyArgs } },
    .{ "qt6_allow_non_utf8_sources", .{ .options = &.{ "INTERFACE_ONLY", "PRIVATE_ONLY" }, .one = emptyArgs, .multi = &.{"PROPERTIES"} } },
    .{ "qt6_finalize_project", .{ .options = emptyArgs, .one = &.{ "FUNCTION_NAME", "NAME", "OUTPUT_SCRIPT", "SKIP_REASON", "TARGET" }, .multi = emptyArgs } },
    .{ "qt_set_finalizer_mode", .{ .options = &.{ "INTERNAL_INSTALL", "ENABLE", "DISABLE" }, .one = &.{"OUT_VAR"}, .multi = &.{"MODES"} } },
    .{ "qt_finalize_project", .{ .options = emptyArgs, .one = &.{ "FUNCTION_NAME", "NAME", "OUTPUT_SCRIPT", "SKIP_REASON", "TARGET" }, .multi = emptyArgs } },
    .{ "qt_add_executable", .{ .options = &.{ "NO_DEFAULT", "MANUAL_FINALIZATION" }, .one = emptyArgs, .multi = &.{ "INCLUDE", "EXCLUDE", "INCLUDE_BY_TYPE", "EXCLUDE_BY_TYPE" } } },
    .{ "qt6_add_executable", .{ .options = &.{"MANUAL_FINALIZATION"}, .one = emptyArgs, .multi = emptyArgs } },
    .{ "qt_disable_unicode_defines", .{ .options = emptyArgs, .one = &.{ "FUNCTION_NAME", "NAME", "OUTPUT_SCRIPT", "SKIP_REASON", "TARGET" }, .multi = emptyArgs } },
    .{ "qt_deploy_qt_conf", .{ .options = &.{""}, .one = &.{ "FILE", "NEW_RPATH", "PREFIX", "DOC_DIR", "HEADERS_DIR", "LIB_DIR", "LIBEXEC_DIR", "BIN_DIR", "PLUGINS_DIR", "QML_DIR", "ARCHDATA_DIR", "DATA_DIR", "TRANSLATIONS_DIR", "EXAMPLES_DIR", "TESTS_DIR", "SETTINGS_DIR" }, .multi = &.{""} } },
    .{ "qt6_deploy_qt_conf", .{ .options = &.{""}, .one = &.{ "PREFIX", "DOC_DIR", "HEADERS_DIR", "LIB_DIR", "LIBEXEC_DIR", "BIN_DIR", "PLUGINS_DIR", "QML_DIR", "ARCHDATA_DIR", "DATA_DIR", "TRANSLATIONS_DIR", "EXAMPLES_DIR", "TESTS_DIR", "SETTINGS_DIR" }, .multi = &.{""} } },
    .{ "qt6_deploy_runtime_dependencies", .{ .options = &.{ "GENERATE_QT_CONF", "VERBOSE", "NO_OVERWRITE", "NO_APP_STORE_COMPLIANCE", "NO_TRANSLATIONS", "NO_COMPILER_RUNTIME" }, .one = &.{ "EXECUTABLE", "BIN_DIR", "LIB_DIR", "LIBEXEC_DIR", "PLUGINS_DIR", "QML_DIR" }, .multi = &.{ "ADDITIONAL_EXECUTABLES", "ADDITIONAL_LIBRARIES", "ADDITIONAL_MODULES", "DEPLOY_TOOL_OPTIONS" } } },
    .{ "qt_deploy_runtime_dependencies", .{ .options = &.{ "", "GENERATE_QT_CONF", "VERBOSE", "NO_OVERWRITE", "NO_APP_STORE_COMPLIANCE", "NO_TRANSLATIONS", "NO_COMPILER_RUNTIME" }, .one = &.{ "EXTRA_MESSAGE", "EXECUTABLE", "BIN_DIR", "LIB_DIR", "LIBEXEC_DIR", "PLUGINS_DIR", "QML_DIR" }, .multi = &.{ "", "ADDITIONAL_EXECUTABLES", "ADDITIONAL_LIBRARIES", "ADDITIONAL_MODULES", "DEPLOY_TOOL_OPTIONS" } } },
    .{ "qt6_deploy_translations", .{ .options = &.{"VERBOSE"}, .one = &.{"LCONVERT"}, .multi = &.{ "CATALOGS", "LOCALES" } } },
    .{ "kirigami_package_breeze_icons", .{ .options = emptyArgs, .one = emptyArgs, .multi = &.{"ICONS"} } },
    .{ "qtquick_compiler_determine_output_filename", .{ .options = emptyArgs, .one = emptyArgs, .multi = &.{"OPTIONS"} } },
    .{ "qtquick_compiler_add_resources", .{ .options = emptyArgs, .one = emptyArgs, .multi = &.{"OPTIONS"} } },
    .{ "qt_deploy_qml_imports", .{ .options = &.{"NO_QT_IMPORTS"}, .one = &.{ "PLUGINS_FOUND", "TARGET", "PLUGINS_DIR", "QML_DIR" }, .multi = &.{""} } },
    .{ "qt6_deploy_qml_imports", .{ .options = &.{"NO_QT_IMPORTS"}, .one = &.{ "TARGET", "PLUGINS_DIR", "QML_DIR", "PLUGINS_FOUND" }, .multi = &.{""} } },
    .{ "qt_import_qml_plugins", .{ .options = &.{ "NO_UNSUPPORTED_PLATFORM_ERROR", "NO_TRANSLATIONS", "NO_COMPILER_RUNTIME", "MACOS_BUNDLE_POST_BUILD", "DEPLOY_USER_QML_MODULES_ON_UNSUPPORTED_PLATFORM" }, .one = &.{ "TARGET", "OUTPUT_SCRIPT", "FILENAME_VARIABLE" }, .multi = &.{ "PRE_INCLUDE_REGEXES", "PRE_EXCLUDE_REGEXES", "POST_INCLUDE_REGEXES", "POST_EXCLUDE_REGEXES", "POST_INCLUDE_FILES", "POST_EXCLUDE_FILES", "DEPLOY_TOOL_OPTIONS" } } },
    .{ "qt_add_qml_module", .{ .options = &.{ "STATIC", "SHARED", "DESIGNER_SUPPORTED", "FOLLOW_FOREIGN_VERSIONING", "AUTO_RESOURCE_PREFIX", "NO_PLUGIN", "NO_PLUGIN_OPTIONAL", "NO_CREATE_PLUGIN_TARGET", "NO_GENERATE_PLUGIN_SOURCE", "NO_GENERATE_QMLTYPES", "NO_GENERATE_QMLDIR", "NO_GENERATE_EXTRA_QMLDIRS", "NO_LINT", "NO_CACHEGEN", "NO_RESOURCE_TARGET_PATH", "NO_IMPORT_SCAN", "ENABLE_TYPE_COMPILER", "__QT_INTERNAL_STATIC_MODULE", "__QT_INTERNAL_SYSTEM_MODULE", "__QT_INTERNAL_DISAMBIGUATE_QMLDIR_RESOURCE" }, .one = &.{ "OUTPUT_TARGETS", "PLUGIN_TARGET", "INSTALLED_PLUGIN_TARGET", "RESOURCE_PREFIX", "URI", "TARGET_PATH", "VERSION", "OUTPUT_DIRECTORY", "CLASS_NAME", "TYPEINFO", "NAMESPACE", "RESOURCE_EXPORT", "INSTALL_DIRECTORY", "INSTALL_LOCATION", "TYPE_COMPILER_NAMESPACE", "QMLTC_EXPORT_DIRECTIVE", "QMLTC_EXPORT_FILE_NAME" }, .multi = &.{ "SOURCES", "QML_FILES", "RESOURCES", "IMPORTS", "IMPORT_PATH", "OPTIONAL_IMPORTS", "DEFAULT_IMPORTS", "DEPENDENCIES", "PAST_MAJOR_VERSIONS" } } },
    .{ "qt6_target_qml_sources", .{ .options = &.{ "NO_LINT", "NO_CACHEGEN", "NO_QMLDIR_TYPES", "__QT_INTERNAL_FORCE_DEFER_QMLDIR", "ADDING_QML_MODULE" }, .one = &.{ "PREFIX", "OUTPUT_TARGETS" }, .multi = &.{ "QML_FILES", "RESOURCES" } } },
    .{ "qt_qml_type_registration", .{ .options = emptyArgs, .one = &.{ "CLASSNAME", "NAME", "PATH", "PLUGIN", "RELATIVEPATH", "TYPE", "VERSION", "LINKTARGET", "PREFER" }, .multi = &.{ "COMPONENTS", "SCRIPTS" } } },
    .{ "qt6_import_qml_plugins", .{ .options = &.{ "NO_UNSUPPORTED_PLATFORM_ERROR", "NO_TRANSLATIONS", "NO_COMPILER_RUNTIME", "MACOS_BUNDLE_POST_BUILD", "DEPLOY_USER_QML_MODULES_ON_UNSUPPORTED_PLATFORM" }, .one = &.{ "TARGET", "OUTPUT_SCRIPT", "FILENAME_VARIABLE" }, .multi = &.{ "PRE_INCLUDE_REGEXES", "PRE_EXCLUDE_REGEXES", "POST_INCLUDE_REGEXES", "POST_EXCLUDE_REGEXES", "POST_INCLUDE_FILES", "POST_EXCLUDE_FILES", "DEPLOY_TOOL_OPTIONS" } } },
    .{ "qt6_generate_foreign_qml_types", .{ .options = emptyArgs, .one = &.{ "NAMESPACE", "REGISTRATIONS_TARGET" }, .multi = &.{"MANUAL_MOC_JSON_FILES"} } },
    .{ "qt_generate_foreign_qml_types", .{ .options = emptyArgs, .one = &.{ "NAMESPACE", "REGISTRATIONS_TARGET" }, .multi = &.{"MANUAL_MOC_JSON_FILES"} } },
    .{ "qt6_target_compile_qml_to_cpp", .{ .options = &.{ "STATIC", "SHARED", "NO_GENERATE_PLUGIN_SOURCE" }, .one = &.{ "OUTPUT_DIRECTORY", "URI", "BACKING_TARGET", "CLASS_NAME", "NAMESPACE", "TARGET_PATH" }, .multi = &.{""} } },
    .{ "qt_add_qml_plugin", .{ .options = &.{ "NO_LINT", "NO_CACHEGEN", "NO_QMLDIR_TYPES", "__QT_INTERNAL_FORCE_DEFER_QMLDIR", "ADDING_QML_MODULE", "STATIC", "SHARED", "NO_GENERATE_PLUGIN_SOURCE" }, .one = &.{ "PREFIX", "OUTPUT_TARGETS", "OUTPUT_DIRECTORY", "URI", "BACKING_TARGET", "CLASS_NAME", "NAMESPACE", "TARGET_PATH" }, .multi = &.{ "QML_FILES", "RESOURCES", "" } } },
    .{ "qt6_query_qml_module", .{ .options = &.{""}, .one = &.{ "URI", "VERSION", "PLUGIN_TARGET", "MODULE_RESOURCE_PATH", "TARGET_PATH", "QMLDIR", "TYPEINFO", "QML_FILES", "QML_FILES_DEPLOY_PATHS", "QML_FILES_PREFIX_OVERRIDES", "RESOURCES", "RESOURCES_DEPLOY_PATHS", "RESOURCES_PREFIX_OVERRIDES" }, .multi = &.{""} } },
    .{ "qt6_qml_type_registration", .{ .options = emptyArgs, .one = &.{ "CLASSNAME", "NAME", "PATH", "PLUGIN", "RELATIVEPATH", "TYPE", "VERSION", "LINKTARGET", "PREFER" }, .multi = &.{ "COMPONENTS", "SCRIPTS" } } },
    .{ "qt6_generate_deploy_qml_app_script", .{ .options = &.{ "NO_UNSUPPORTED_PLATFORM_ERROR", "NO_TRANSLATIONS", "NO_COMPILER_RUNTIME", "MACOS_BUNDLE_POST_BUILD", "DEPLOY_USER_QML_MODULES_ON_UNSUPPORTED_PLATFORM" }, .one = &.{ "TARGET", "OUTPUT_SCRIPT", "FILENAME_VARIABLE" }, .multi = &.{ "PRE_INCLUDE_REGEXES", "PRE_EXCLUDE_REGEXES", "POST_INCLUDE_REGEXES", "POST_EXCLUDE_REGEXES", "POST_INCLUDE_FILES", "POST_EXCLUDE_FILES", "DEPLOY_TOOL_OPTIONS" } } },
    .{ "qt_target_compile_qml_to_cpp", .{ .options = &.{ "STATIC", "SHARED", "NO_GENERATE_PLUGIN_SOURCE" }, .one = &.{ "OUTPUT_DIRECTORY", "URI", "BACKING_TARGET", "CLASS_NAME", "NAMESPACE", "TARGET_PATH" }, .multi = &.{""} } },
    .{ "qt6_add_qml_module", .{ .options = &.{ "STATIC", "SHARED", "DESIGNER_SUPPORTED", "FOLLOW_FOREIGN_VERSIONING", "AUTO_RESOURCE_PREFIX", "NO_PLUGIN", "NO_PLUGIN_OPTIONAL", "NO_CREATE_PLUGIN_TARGET", "NO_GENERATE_PLUGIN_SOURCE", "NO_GENERATE_QMLTYPES", "NO_GENERATE_QMLDIR", "NO_GENERATE_EXTRA_QMLDIRS", "NO_LINT", "NO_CACHEGEN", "NO_RESOURCE_TARGET_PATH", "NO_IMPORT_SCAN", "ENABLE_TYPE_COMPILER", "__QT_INTERNAL_STATIC_MODULE", "__QT_INTERNAL_SYSTEM_MODULE", "__QT_INTERNAL_DISAMBIGUATE_QMLDIR_RESOURCE" }, .one = &.{ "PLUGIN_TARGET", "INSTALLED_PLUGIN_TARGET", "OUTPUT_TARGETS", "RESOURCE_PREFIX", "URI", "TARGET_PATH", "VERSION", "OUTPUT_DIRECTORY", "CLASS_NAME", "TYPEINFO", "NAMESPACE", "RESOURCE_EXPORT", "INSTALL_DIRECTORY", "INSTALL_LOCATION", "TYPE_COMPILER_NAMESPACE", "QMLTC_EXPORT_DIRECTIVE", "QMLTC_EXPORT_FILE_NAME" }, .multi = &.{ "SOURCES", "QML_FILES", "RESOURCES", "IMPORTS", "IMPORT_PATH", "OPTIONAL_IMPORTS", "DEFAULT_IMPORTS", "DEPENDENCIES", "PAST_MAJOR_VERSIONS" } } },
    .{ "qt6_add_qml_plugin", .{ .options = &.{ "STATIC", "SHARED", "NO_GENERATE_PLUGIN_SOURCE" }, .one = &.{ "OUTPUT_DIRECTORY", "URI", "BACKING_TARGET", "CLASS_NAME", "NAMESPACE", "TARGET_PATH" }, .multi = &.{""} } },
    .{ "qt_target_qml_sources", .{ .options = &.{ "NO_LINT", "NO_CACHEGEN", "NO_QMLDIR_TYPES", "__QT_INTERNAL_FORCE_DEFER_QMLDIR", "ADDING_QML_MODULE" }, .one = &.{ "OUTPUT_TARGETS", "PREFIX" }, .multi = &.{ "QML_FILES", "RESOURCES" } } },
    .{ "qt5_add_statecharts", .{ .options = emptyArgs, .one = emptyArgs, .multi = &.{"OPTIONS"} } },
    .{ "kcmutils_add_qml_kcm", .{ .options = &.{"DISABLE_DESKTOP_FILE_GENERATION"}, .one = &.{"INSTALL_NAMESPACE"}, .multi = &.{"SOURCES"} } },
    .{ "kcmutils_generate_module_data", .{ .options = emptyArgs, .one = &.{ "MODULE_DATA_CLASS_NAME", "MODULE_DATA_HEADER", "NAMESPACE" }, .multi = &.{ "SETTINGS_HEADERS", "SETTINGS_CLASSES" } } },
    .{ "kcmutils_generate_desktop_file", .{ .options = &.{"DISABLE_DESKTOP_FILE_GENERATION"}, .one = &.{"INSTALL_NAMESPACE"}, .multi = &.{"SOURCES"} } },
    .{ "qt_skip_warnings_are_errors_when_repo_unclean", .{ .options = &.{"REGEX"}, .one = emptyArgs, .multi = emptyArgs } },
    .{ "qt_set_language_standards_interface_compile_features", .{ .options = &.{"REGEX"}, .one = emptyArgs, .multi = emptyArgs } },
    .{ "qt_skip_warnings_are_errors", .{ .options = &.{"REGEX"}, .one = emptyArgs, .multi = emptyArgs } },
    .{ "qt_set_symbol_visibility_hidden", .{ .options = &.{"REGEX"}, .one = emptyArgs, .multi = emptyArgs } },
    .{ "qt_disable_warnings", .{ .options = &.{"REGEX"}, .one = emptyArgs, .multi = emptyArgs } },
    .{ "qt_set_msvc_cplusplus_options", .{ .options = &.{"REGEX"}, .one = emptyArgs, .multi = emptyArgs } },
    .{ "qt_enable_utf8_sources", .{ .options = &.{"REGEX"}, .one = emptyArgs, .multi = emptyArgs } },
    .{ "qt_set_language_standards", .{ .options = &.{"REGEX"}, .one = emptyArgs, .multi = emptyArgs } },
    .{ "qt_set_symbol_visibility_preset", .{ .options = &.{"REGEX"}, .one = emptyArgs, .multi = emptyArgs } },
    .{ "qt_enable_separate_debug_info", .{ .options = &.{"QT_EXECUTABLE"}, .one = &.{"DSYM_OUTPUT_DIR"}, .multi = &.{"ADDITIONAL_INSTALL_ARGS"} } },
    .{ "ecm_add_wayland_client_protocol", .{ .options = emptyArgs, .one = &.{ "PROTOCOL", "BASENAME" }, .multi = emptyArgs } },
    .{ "ecm_add_wayland_server_protocol", .{ .options = emptyArgs, .one = &.{ "PROTOCOL", "BASENAME" }, .multi = emptyArgs } },
    .{ "qt_build_internals_add_toplevel_targets", .{ .options = emptyArgs, .one = &.{"DEPENDS"}, .multi = emptyArgs } },
    .{ "qt_install_3rdparty_library_wrap_config_extra_file", .{ .options = emptyArgs, .one = &.{"EXTERNAL_HEADERS_DIR"}, .multi = &.{"EXTERNAL_HEADERS"} } },
    .{ "qt_configure_print_build_instructions_helper", .{ .options = &.{"RECORD_ON_FEATURE_EVALUATION"}, .one = emptyArgs, .multi = emptyArgs } },
    .{ "qt_configure_print_summary_helper", .{ .options = &.{"RECORD_ON_FEATURE_EVALUATION"}, .one = emptyArgs, .multi = emptyArgs } },
    .{ "qt_configure_process_add_summary_build_parts", .{ .options = emptyArgs, .one = &.{"NAME"}, .multi = emptyArgs } },
    .{ "qt_configure_add_report_entry", .{ .options = emptyArgs, .one = &.{ "TYPE", "MESSAGE" }, .multi = &.{"CONDITION"} } },
    .{ "qt_print_build_instructions", .{ .options = &.{"RECORD_ON_FEATURE_EVALUATION"}, .one = emptyArgs, .multi = emptyArgs } },
    .{ "qt_configure_eval_commands", .{ .options = emptyArgs, .one = &.{ "PADDING_LENGTH", "MIN_PADDING" }, .multi = emptyArgs } },
    .{ "qt_configure_add_summary_build_type_and_config", .{ .options = emptyArgs, .one = &.{"NAME"}, .multi = emptyArgs } },
    .{ "qt_configure_record_command", .{ .options = &.{"RECORD_ON_FEATURE_EVALUATION"}, .one = emptyArgs, .multi = emptyArgs } },
    .{ "qt_configure_process_add_summary_entry", .{ .options = emptyArgs, .one = &.{ "ARGS", "TYPE", "MESSAGE" }, .multi = &.{"CONDITION"} } },
    .{ "qt_configure_end_summary_section", .{ .options = emptyArgs, .one = &.{ "TYPE", "MESSAGE" }, .multi = &.{"CONDITION"} } },
    .{ "qt_configure_add_summary_section", .{ .options = emptyArgs, .one = &.{"NAME"}, .multi = emptyArgs } },
    .{ "qt_configure_process_end_summary_section", .{ .options = emptyArgs, .one = &.{ "TYPE", "MESSAGE" }, .multi = &.{"CONDITION"} } },
    .{ "qt_configure_add_report_error", .{ .options = emptyArgs, .one = &.{ "TYPE", "MESSAGE" }, .multi = &.{"CONDITION"} } },
    .{ "qt_configure_add_summary_build_parts", .{ .options = emptyArgs, .one = &.{"NAME"}, .multi = emptyArgs } },
    .{ "qt_configure_get_padded_string", .{ .options = emptyArgs, .one = &.{ "PADDING_LENGTH", "MIN_PADDING" }, .multi = emptyArgs } },
    .{ "qt_configure_print_summary", .{ .options = &.{"RECORD_ON_FEATURE_EVALUATION"}, .one = emptyArgs, .multi = emptyArgs } },
    .{ "qt_configure_process_add_summary_build_mode", .{ .options = emptyArgs, .one = &.{"NAME"}, .multi = emptyArgs } },
    .{ "qt_print_feature_summary", .{ .options = &.{"RECORD_ON_FEATURE_EVALUATION"}, .one = emptyArgs, .multi = emptyArgs } },
    .{ "qt_configure_process_add_summary_build_type_and_config", .{ .options = emptyArgs, .one = &.{"NAME"}, .multi = emptyArgs } },
    .{ "qt_configure_process_add_summary_section", .{ .options = emptyArgs, .one = &.{"NAME"}, .multi = emptyArgs } },
    .{ "qt_configure_add_summary_build_mode", .{ .options = emptyArgs, .one = &.{"NAME"}, .multi = emptyArgs } },
    .{ "qt_configure_process_add_report_entry", .{ .options = emptyArgs, .one = &.{ "TYPE", "MESSAGE" }, .multi = &.{"CONDITION"} } },
    .{ "qt_configure_add_summary_entry", .{ .options = emptyArgs, .one = &.{ "ARGS", "TYPE", "MESSAGE" }, .multi = &.{"CONDITION"} } },
    .{ "qt_copy_framework_headers", .{ .options = emptyArgs, .one = emptyArgs, .multi = &.{ "PUBLIC", "PRIVATE", "QPA", "RHI", "SSG" } } },
    .{ "qt_get_install_target_default_args", .{ .options = emptyArgs, .one = &.{ "OUT_VAR", "OUT_VAR_RUNTIME", "CMAKE_CONFIG", "RUNTIME", "LIBRARY", "ARCHIVE", "INCLUDES", "BUNDLE" }, .multi = &.{"ALL_CMAKE_CONFIGS"} } },
    .{ "qt_disable_apple_app_extension_api_only", .{ .options = &.{""}, .one = &.{ "EXPORT_NAME_PREFIX", "CONFIG_INSTALL_DIR" }, .multi = &.{"TARGETS"} } },
    .{ "qt_get_direct_module_dependencies", .{ .options = &.{"PRIVATE"}, .one = emptyArgs, .multi = emptyArgs } },
    .{ "qt_generate_module_pri_file", .{ .options = &.{ "INTERNAL_MODULE", "NO_PRIVATE_MODULE" }, .one = emptyArgs, .multi = emptyArgs } },
    .{ "qt_generate_qmake_libraries_pri_content", .{ .options = &.{"PRIVATE"}, .one = emptyArgs, .multi = emptyArgs } },
    .{ "qt_create_qdbusxml2cpp_command", .{ .options = &.{ "ADAPTOR", "INTERFACE" }, .one = &.{"BASENAME"}, .multi = &.{"FLAGS"} } },
    .{ "qt_manual_moc", .{ .options = emptyArgs, .one = &.{"OUTPUT_MOC_JSON_FILES"}, .multi = &.{ "FLAGS", "INCLUDE_DIRECTORIES", "INCLUDE_DIRECTORY_TARGETS", "DEFINITIONS", "TARGETS" } } },
    .{ "qt_copy_or_install", .{ .options = &.{ "FILES", "PROGRAMS", "DIRECTORY" }, .one = emptyArgs, .multi = emptyArgs } },
    .{ "qt_install", .{ .options = emptyArgs, .one = &.{ "EXPORT", "DESTINATION", "NAMESPACE" }, .multi = &.{"TARGETS"} } },
    .{ "qt_get_install_executable_permissions", .{ .options = &.{ "FILES", "PROGRAMS", "DIRECTORY" }, .one = emptyArgs, .multi = emptyArgs } },
    .{ "qt_non_prefix_copy", .{ .options = &.{ "FILES", "PROGRAMS", "DIRECTORY" }, .one = emptyArgs, .multi = emptyArgs } },
    .{ "qt_feature_module_end", .{ .options = &.{"ONLY_EVALUATE_FEATURES"}, .one = &.{"OUT_VAR_PREFIX"}, .multi = emptyArgs } },
    .{ "qt_feature_copy_global_config_features_to_core", .{ .options = emptyArgs, .one = &.{ "LABEL", "PROJECT_PATH", "C_STANDARD", "CXX_STANDARD" }, .multi = &.{ "COMPILE_OPTIONS", "LIBRARIES", "CODE", "PACKAGES", "CMAKE_FLAGS" } } },
    .{ "qt_config_compile_test_x86simd", .{ .options = emptyArgs, .one = &.{ "LABEL", "FLAG" }, .multi = emptyArgs } },
    .{ "qt_config_compile_test_machine_tuple", .{ .options = emptyArgs, .one = &.{ "LABEL", "FLAG" }, .multi = emptyArgs } },
    .{ "qt_extra_definition", .{ .options = &.{ "PUBLIC", "PRIVATE" }, .one = emptyArgs, .multi = emptyArgs } },
    .{ "qt_feature_evaluate_features", .{ .options = &.{"ONLY_EVALUATE_FEATURES"}, .one = &.{"OUT_VAR_PREFIX"}, .multi = emptyArgs } },
    .{ "qt_config_compile_test", .{ .options = emptyArgs, .one = &.{ "LABEL", "PROJECT_PATH", "C_STANDARD", "CXX_STANDARD" }, .multi = &.{ "COMPILE_OPTIONS", "LIBRARIES", "CODE", "PACKAGES", "CMAKE_FLAGS" } } },
    .{ "qt_config_compiler_supports_flag_test", .{ .options = emptyArgs, .one = &.{ "LABEL", "FLAG" }, .multi = emptyArgs } },
    .{ "qt_evaluate_config_expression", .{ .options = &.{ "PRIVATE", "PUBLIC" }, .one = &.{ "LABEL", "PURPOSE", "SECTION", "" }, .multi = &.{ "AUTODETECT", "CONDITION", "ENABLE", "DISABLE", "EMIT_IF" } } },
    .{ "qt_feature_definition", .{ .options = &.{"NEGATE"}, .one = &.{ "VALUE", "PREREQUISITE" }, .multi = emptyArgs } },
    .{ "qt_feature_config", .{ .options = &.{"NEGATE"}, .one = &.{"NAME"}, .multi = emptyArgs } },
    .{ "qt_feature_module_begin", .{ .options = &.{ "NO_MODULE", "ONLY_EVALUATE_FEATURES" }, .one = &.{ "LIBRARY", "PRIVATE_FILE", "PUBLIC_FILE" }, .multi = &.{ "PUBLIC_DEPENDENCIES", "PRIVATE_DEPENDENCIES" } } },
    .{ "qt_feature", .{ .options = &.{ "PRIVATE", "PUBLIC" }, .one = &.{ "LABEL", "PURPOSE", "SECTION" }, .multi = &.{ "AUTODETECT", "CONDITION", "ENABLE", "DISABLE", "EMIT_IF" } } },
    .{ "qt_get_platform_try_compile_vars", .{ .options = emptyArgs, .one = &.{ "LABEL", "FLAG" }, .multi = emptyArgs } },
    .{ "qt_evaluate_feature_definition", .{ .options = &.{ "NEGATE", "" }, .one = &.{ "FEATURE", "NAME", "VALUE", "PREREQUISITE" }, .multi = emptyArgs } },
    .{ "qt_config_linker_supports_flag_test", .{ .options = emptyArgs, .one = &.{ "LABEL", "FLAG" }, .multi = emptyArgs } },
    .{ "qt_evaluate_qmake_config_values", .{ .options = &.{"NEGATE"}, .one = &.{ "FEATURE", "NAME", "CONFIG_VAR_NAME" }, .multi = emptyArgs } },
    .{ "qt_evaluate_feature", .{ .options = &.{"NEGATE"}, .one = &.{"NAME"}, .multi = emptyArgs } },
    .{ "qt_evaluate_to_boolean", .{ .options = &.{ "PRIVATE", "PUBLIC" }, .one = &.{ "LABEL", "PURPOSE", "SECTION", "" }, .multi = &.{ "AUTODETECT", "CONDITION", "ENABLE", "DISABLE", "EMIT_IF" } } },
    .{ "qt_feature_record_summary_entries", .{ .options = &.{"ONLY_EVALUATE_FEATURES"}, .one = &.{"OUT_VAR_PREFIX"}, .multi = emptyArgs } },
    .{ "qt_feature_check_and_save_user_provided_value", .{ .options = &.{ "PRIVATE", "PUBLIC" }, .one = &.{ "LABEL", "PURPOSE", "SECTION", "" }, .multi = &.{ "AUTODETECT", "CONDITION", "ENABLE", "DISABLE", "EMIT_IF" } } },
    .{ "qt_describe_module", .{ .options = emptyArgs, .one = &.{"CPP_EXPORT_HEADER_BASE_NAME"}, .multi = emptyArgs } },
    .{ "qt_finalize_module", .{ .options = emptyArgs, .one = &.{"CPP_EXPORT_HEADER_BASE_NAME"}, .multi = emptyArgs } },
    .{ "qt_finalize_plugin", .{ .options = emptyArgs, .one = &.{"INSTALL_PATH"}, .multi = emptyArgs } },
    .{ "qt6_add_statecharts", .{ .options = emptyArgs, .one = &.{ "OUTPUT_DIR", "OUTPUT_DIRECTORY", "NAMESPACE" }, .multi = &.{ "QSCXMLC_ARGUMENTS", "OPTIONS" } } },
    .{ "qt6_add_webengine_dictionary", .{ .options = emptyArgs, .one = &.{ "TARGET", "SOURCE", "OUTPUT_DIRECTORY" }, .multi = emptyArgs } },
    .{ "qt_add_dbus_interface", .{ .options = emptyArgs, .one = emptyArgs, .multi = &.{"OPTIONS"} } },
    .{ "qt_add_dbus_interfaces", .{ .options = emptyArgs, .one = emptyArgs, .multi = &.{"OPTIONS"} } },
    .{ "qt6_add_dbus_interface", .{ .options = emptyArgs, .one = emptyArgs, .multi = &.{"OPTIONS"} } },
    .{ "qt6_generate_dbus_interface", .{ .options = emptyArgs, .one = emptyArgs, .multi = &.{"OPTIONS"} } },
    .{ "qt6_add_dbus_interfaces", .{ .options = emptyArgs, .one = emptyArgs, .multi = &.{"OPTIONS"} } },
    .{ "kconfig_add_kcfg_files", .{ .options = &.{ "GENERATE_MOC", "USE_RELATIVE_PATH" }, .one = emptyArgs, .multi = emptyArgs } },
    .{ "kconfig_target_kcfg_file", .{ .options = &.{ "MUTATORS", "SINGLETON", "CUSTOM_ADDITIONS", "NOTIFIERS", "DEFAULT_VALUE_GETTERS", "ITEM_ACCESSORS", "SET_USER_TEXTS", "GLOBAL_ENUMS", "USE_ENUM_TYPES", "FORCE_STRING_FILENAME", "GENERATE_PROPERTIES", "PARENT_IN_CONSTRUCTOR", "GENERATE_MOC", "QML_REGISTRATION" }, .one = &.{ "FILE", "CLASS_NAME", "VISIBILITY", "HEADER_EXTENSION", "SOURCE_EXTENSION", "NAME_SPACE", "INHERITS", "MEMBER_VARIABLES", "TRANSLATION_SYSTEM", "TRANSLATION_DOMAIN" }, .multi = &.{ "INCLUDE_FILES", "SOURCE_INCLUDE_FILES" } } },
    .{ "qt5_add_translation", .{ .options = emptyArgs, .one = emptyArgs, .multi = &.{ "OPTIONS", "__QT_INTERNAL_TIMESTAMP_FILES" } } },
    .{ "qt5_create_translation", .{ .options = emptyArgs, .one = emptyArgs, .multi = &.{"OPTIONS"} } },
    .{ "qt_create_translation", .{ .options = emptyArgs, .one = emptyArgs, .multi = &.{ "OPTIONS", "__QT_INTERNAL_TIMESTAMP_FILES" } } },
    .{ "qt5_add_big_resources", .{ .options = emptyArgs, .one = emptyArgs, .multi = &.{"OPTIONS"} } },
    .{ "qt5_add_resources", .{ .options = emptyArgs, .one = emptyArgs, .multi = &.{"OPTIONS"} } },
    .{ "qt_generate_moc", .{ .options = emptyArgs, .one = &.{"TARGET"}, .multi = &.{ "OPTIONS", "DEPENDS" } } },
    .{ "qt_add_resources", .{ .options = emptyArgs, .one = emptyArgs, .multi = &.{"OPTIONS"} } },
    .{ "qt5_create_moc_command", .{ .options = emptyArgs, .one = &.{"TARGET"}, .multi = &.{ "OPTIONS", "DEPENDS" } } },
    .{ "qt5_wrap_cpp", .{ .options = emptyArgs, .one = &.{"TARGET"}, .multi = &.{ "OPTIONS", "DEPENDS" } } },
    .{ "qt5_add_binary_resources", .{ .options = emptyArgs, .one = &.{"DESTINATION"}, .multi = &.{"OPTIONS"} } },
    .{ "qt_add_binary_resources", .{ .options = emptyArgs, .one = &.{"DESTINATION"}, .multi = &.{"OPTIONS"} } },
    .{ "qt5_generate_moc", .{ .options = emptyArgs, .one = &.{"TARGET"}, .multi = &.{ "OPTIONS", "DEPENDS" } } },
    .{ "qt_wrap_cpp", .{ .options = emptyArgs, .one = &.{ "DESTINATION", "TARGET" }, .multi = &.{ "OPTIONS", "DEPENDS" } } },
    .{ "qt5_generate_dbus_interface", .{ .options = emptyArgs, .one = emptyArgs, .multi = &.{"OPTIONS"} } },
    .{ "qt5_add_dbus_interfaces", .{ .options = emptyArgs, .one = emptyArgs, .multi = &.{"OPTIONS"} } },
    .{ "qt_add_dbus_interface", .{ .options = emptyArgs, .one = emptyArgs, .multi = &.{"OPTIONS"} } },
    .{ "qt_add_dbus_interfaces", .{ .options = emptyArgs, .one = emptyArgs, .multi = &.{"OPTIONS"} } },
    .{ "qt5_add_dbus_interface", .{ .options = emptyArgs, .one = emptyArgs, .multi = &.{"OPTIONS"} } },
    .{ "qt6_wrap_ui", .{ .options = emptyArgs, .one = emptyArgs, .multi = &.{"OPTIONS"} } },
    .{ "qt_wrap_ui", .{ .options = emptyArgs, .one = &.{"INCLUDE_PREFIX"}, .multi = &.{ "SOURCES", "OPTIONS" } } },
    .{ "qt6_add_ui", .{ .options = emptyArgs, .one = &.{"INCLUDE_PREFIX"}, .multi = &.{ "SOURCES", "OPTIONS" } } },

    // ECM
    .{ "ecm_add_qtwayland_client_protocol", .{ .options = &.{"PRIVATE_CODE"}, .one = &.{ "PROTOCOL", "BASENAME", "PREFIX" }, .multi = emptyArgs } },
    .{ "ecm_add_qtwayland_server_protocol", .{ .options = &.{"PRIVATE_CODE"}, .one = &.{ "PROTOCOL", "BASENAME", "PREFIX" }, .multi = emptyArgs } },
    .{ "ecm_gperf_generate", .{ .options = emptyArgs, .one = &.{"GENERATION_FLAGS"}, .multi = emptyArgs } },
    .{ "ecm_add_wayland_client_protocol", .{ .options = &.{"PRIVATE_CODE"}, .one = &.{ "PROTOCOL", "BASENAME" }, .multi = emptyArgs } },
    .{ "ecm_add_wayland_server_protocol", .{ .options = &.{"PRIVATE_CODE"}, .one = &.{ "PROTOCOL", "BASENAME" }, .multi = emptyArgs } },
    .{ "gradle_add_aar", .{ .options = emptyArgs, .one = &.{ "BUILDFILE", "NAME" }, .multi = emptyArgs } },
    .{ "gradle_install_aar", .{ .options = emptyArgs, .one = &.{"DESTINATION"}, .multi = emptyArgs } },
    .{ "ecm_process_po_files_as_qm", .{ .options = &.{"ALL"}, .one = &.{"INSTALL_DESTINATION"}, .multi = &.{"PO_FILES"} } },
    .{ "ecm_create_qm_loader", .{ .options = &.{"ALL"}, .one = &.{"INSTALL_DESTINATION"}, .multi = &.{"PO_FILES"} } },
    .{ "ecm_generate_pkgconfig_file", .{ .options = &.{"INSTALL"}, .one = &.{ "BASE_NAME", "LIB_NAME", "FILENAME_VAR", "INCLUDE_INSTALL_DIR", "LIB_INSTALL_DIR", "DESCRIPTION", "URL" }, .multi = &.{ "DEPS", "DEFINES" } } },
    .{ "ecm_find_qmlmodule", .{ .options = &.{"REQUIRED"}, .one = emptyArgs, .multi = emptyArgs } },
    .{ "ecm_configure_package_config_file", .{ .options = &.{ "NO_SET_AND_CHECK_MACRO", "NO_CHECK_REQUIRED_COMPONENTS_MACRO" }, .one = &.{"INSTALL_DESTINATION"}, .multi = &.{"PATH_VARS"} } },
    .{ "ecm_install_qch_export", .{ .options = emptyArgs, .one = &.{ "FILE", "DESTINATION", "COMPONENT" }, .multi = &.{"TARGETS"} } },
    .{ "ecm_add_qch", .{ .options = &.{"VERBOSE"}, .one = &.{ "NAME", "BASE_NAME", "QCH_INSTALL_DESTINATION", "TAGFILE_INSTALL_DESTINATION", "COMPONENT", "VERSION", "NAMESPACE", "MD_MAINPAGE", "ORG_DOMAIN", "CONFIG_TEMPLATE" }, .multi = &.{ "SOURCE_DIRS", "SOURCES", "INCLUDE_DIRS", "IMAGE_DIRS", "EXAMPLE_DIRS", "PREDEFINED_MACROS", "BLANK_MACROS", "LINK_QCHS" } } },
    .{ "ecm_export_header_format_version", .{ .options = emptyArgs, .one = &.{ "CURRENT_VERSION", "STRING_VAR", "HEXNUMBER_VAR" }, .multi = emptyArgs } },
    .{ "ecm_generate_export_header", .{ .options = &.{ "NO_DEFINITION_EXPORT_TO_BUILD_INTERFACE", "NO_BUILD_SET_DEPRECATED_WARNINGS_SINCE" }, .one = &.{ "BASE_NAME", "GROUP_BASE_NAME", "EXPORT_FILE_NAME", "DEPRECATED_BASE_VERSION", "VERSION", "VERSION_BASE_NAME", "VERSION_MACRO_NAME", "EXCLUDE_DEPRECATED_BEFORE_AND_AT", "EXPORT_MACRO_NAME", "DEPRECATED_MACRO_NAME", "NO_EXPORT_MACRO_NAME", "INCLUDE_GUARD_NAME", "STATIC_DEFINE", "PREFIX_NAME", "CUSTOM_CONTENT_FROM_VARIABLE" }, .multi = &.{ "DEPRECATION_VERSIONS", "USE_VERSION_HEADER" } } },
    .{ "ecm_query_qt", .{ .options = &.{"TRY"}, .one = emptyArgs, .multi = emptyArgs } },
    .{ "ecm_generate_headers", .{ .options = emptyArgs, .one = &.{ "ORIGINAL", "HEADER_EXTENSION", "OUTPUT_DIR", "PREFIX", "REQUIRED_HEADERS", "COMMON_HEADER", "RELATIVE" }, .multi = &.{"HEADER_NAMES"} } },
    .{ "ecm_install_configured_files", .{ .options = &.{ "COPYONLY", "ESCAPE_QUOTES", "@ONLY" }, .one = &.{ "DESTINATION", "COMPONENT" }, .multi = &.{"INPUT"} } },
    .{ "ecm_add_tests", .{ .options = &.{"GUI"}, .one = &.{ "NAME_PREFIX", "TARGET_NAMES_VAR", "TEST_NAMES_VAR", "WORKING_DIRECTORY" }, .multi = &.{"LINK_LIBRARIES"} } },
    .{ "ecm_add_test", .{ .options = &.{"GUI"}, .one = &.{ "TEST_NAME", "NAME_PREFIX", "TARGET_NAME_VAR", "TEST_NAME_VAR", "WORKING_DIRECTORY" }, .multi = &.{"LINK_LIBRARIES"} } },
    .{ "ecm_generate_dbus_service_file", .{ .options = emptyArgs, .one = &.{ "EXECUTABLE", "NAME", "SYSTEMD_SERVICE", "DESTINATION", "RENAME" }, .multi = emptyArgs } },
    .{ "ecm_check_outbound_license", .{ .options = &.{"WILL_FAIL"}, .one = &.{"TEST_NAME"}, .multi = &.{ "LICENSES", "FILES" } } },
    .{ "ecm_create_qm_from_po_files", .{ .options = emptyArgs, .one = &.{ "CATALOG_NAME", "INSTALL_DESTINATION" }, .multi = &.{"PO_FILES"} } },
    .{ "ecm_create_qm_loader", .{ .options = emptyArgs, .one = &.{ "CATALOG_NAME", "INSTALL_DESTINATION" }, .multi = &.{"PO_FILES"} } },
    .{ "ecm_add_app_icon", .{ .options = emptyArgs, .one = &.{"OUTFILE_BASENAME"}, .multi = &.{ "ICONS", "SIDEBAR_ICONS" } } },
    .{ "ecm_generate_python_bindings", .{ .options = emptyArgs, .one = &.{ "PACKAGE_NAME", "WRAPPED_HEADER", "TYPESYSTEM", "VERSION", "QT_VERSION", "HOMEPAGE_URL", "ISSUES_URL", "AUTHOR", "README" }, .multi = &.{ "GENERATED_SOURCES", "DEPENDENCIES" } } },
    .{ "ecm_generate_qmltypes", .{ .options = emptyArgs, .one = &.{ "DESTINATION", "TEST_ENABLED" }, .multi = emptyArgs } },
    .{ "ecm_qt_declare_logging_category", .{ .options = emptyArgs, .one = &.{ "HEADER", "IDENTIFIER", "CATEGORY_NAME", "DEFAULT_SEVERITY", "EXPORT", "DESCRIPTION" }, .multi = &.{"OLD_CATEGORY_NAMES"} } },
    .{ "ecm_qt_export_logging_category", .{ .options = emptyArgs, .one = &.{ "IDENTIFIER", "CATEGORY_NAME", "DEFAULT_SEVERITY", "EXPORT", "DESCRIPTION" }, .multi = &.{"OLD_CATEGORY_NAMES"} } },
    .{ "ecm_qt_install_logging_categories", .{ .options = &.{"SORT"}, .one = &.{ "FILE", "EXPORT", "DESTINATION", "COMPONENT" }, .multi = emptyArgs } },
    .{ "ecm_use_find_modules", .{ .options = &.{"NO_OVERRIDE"}, .one = &.{"DIR"}, .multi = &.{"MODULES"} } },
    .{ "ecm_qtdesignerplugin_widget", .{ .options = &.{"CONTAINER"}, .one = &.{ "CLASS_NAME", "INCLUDE_FILE", "ICON", "TOOLTIP", "WHATSTHIS", "GROUP", "CREATE_WIDGET_CODE_FROM_VARIABLE", "INITIALIZE_CODE_FROM_VARIABLE", "DOM_XML_FROM_VARIABLE", "IMPL_CLASS_NAME", "CONSTRUCTOR_ARGS_CODE", "CONSTRUCTOR_ARGS_CODE_FROM_VARIABLE" }, .multi = emptyArgs } },
    .{ "ecm_setup_version", .{ .options = emptyArgs, .one = &.{ "VARIABLE_PREFIX", "SOVERSION", "VERSION_HEADER", "PACKAGE_VERSION_FILE", "COMPATIBILITY" }, .multi = emptyArgs } },
    .{ "ecm_finalize_qml_module", .{ .options = emptyArgs, .one = &.{"DESTINATION"}, .multi = emptyArgs } },
    .{ "ecm_add_qml_module_dependencies", .{ .options = emptyArgs, .one = emptyArgs, .multi = &.{"DEPENDS"} } },
    .{ "ecm_target_qml_sources", .{ .options = &.{"PRIVATE"}, .one = &.{ "VERSION", "PATH" }, .multi = &.{"SOURCES"} } },
    .{ "ecm_add_qml_module", .{ .options = &.{"NO_PLUGIN"}, .one = &.{ "URI", "VERSION", "CLASSNAME" }, .multi = emptyArgs } },
    .{ "ecm_generate_pri_file", .{ .options = emptyArgs, .one = &.{ "BASE_NAME", "LIB_NAME", "DEPS", "FILENAME_VAR", "INCLUDE_INSTALL_DIR", "LIB_INSTALL_DIR", "VERSION" }, .multi = &.{"INCLUDE_INSTALL_DIRS"} } },
    .{ "query_qmake", .{ .options = &.{"TRY"}, .one = emptyArgs, .multi = emptyArgs } },
    .{ "ecm_install_icons", .{ .options = emptyArgs, .one = &.{ "DESTINATION", "LANG", "THEME" }, .multi = &.{"ICONS"} } },
    .{ "ecm_set_disabled_deprecation_versions", .{ .options = &.{ "SHOW_DEPRECATIONS", "DISABLE_NEWER_WARNINGS" }, .one = emptyArgs, .multi = emptyArgs } },
    .{ "ecm_finalize_qml_module", .{ .options = emptyArgs, .one = &.{ "DESTINATION", "VERSION", "EXPORT" }, .multi = emptyArgs } },
    .{ "ecm_add_qml_module_dependencies", .{ .options = &.{"PRIVATE"}, .one = &.{ "VERSION", "PATH", "OUTPUT_TARGETS" }, .multi = &.{"SOURCES"} } },
    .{ "ecm_target_qml_sources", .{ .options = &.{"PRIVATE"}, .one = &.{ "VERSION", "PATH", "OUTPUT_TARGETS" }, .multi = &.{"SOURCES"} } },
    .{ "ecm_add_qml_module", .{ .options = &.{ "NO_PLUGIN", "QT_NO_PLUGIN", "GENERATE_PLUGIN_SOURCE" }, .one = &.{ "URI", "VERSION", "CLASSNAME", "OUTPUT_TARGETS" }, .multi = emptyArgs } },
    .{ "ecm_add_android_apk", .{ .options = emptyArgs, .one = &.{"ANDROID_DIR"}, .multi = emptyArgs } },
});
